kind: Deployment
apiVersion: extensions/v1beta1
spec:
  template:
    metadata:
      name: example
    spec:
      containers:
      - name: example
        image: ##image##
        ports:
        - name: example
          containerPort: 3000
