apiVersion: apps/v1beta1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: k8s-exaple
  template:
    metadata:
      labels:
        app: k8s-example
    spec:
      containers:
      - name: k8s-example
        image: ##image##
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-example
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector: k8s-example
