apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pr-cleanup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k8s-kubectl
            image: lachlanevenson/k8s-kubectl
            args:
            - /bin/sh
            - -c
            - kubectl get ns -l temp=true | grep '1m' | awk '{ print $1 }' | while read line; do echo "Deleting $line"; kubectl delete ns $line; done
          restartPolicy: Never
